export const ADD_INGREDIENT = 'ADD_INGREDIENT'
export const DELETE_INGREDIENT = 'DELETE_INGREDIENT'
export const SET_INGREDIENTS = 'SET_INGREDIENTS' 
export const FETCH_FAILED = 'FETCH_FAILED' 

export const PURCHASE_SUCCESS = 'PURCHASE_SUCCESS'
export const PURCHASE_FAIL = 'PURCHASE_FAIL'
export const PURCHASE_START = 'PURCHASE_START'