export const ADD_INGREDIENT = 'ADD_INGREDIENT'
export const DELETE_INGREDIENT = 'DELETE_INGREDIENT'
export const SET_INGREDIENTS = 'SET_INGREDIENTS' 
export const FETCH_INGRES_FAILED = 'FETCH_INGRES_FAILED' 

export const PURCHASE_SUCCESS = 'PURCHASE_SUCCESS'
export const PURCHASE_FAIL = 'PURCHASE_FAIL'
export const PURCHASE_START = 'PURCHASE_START'
export const PURCHASE_INIT = 'PURCHASE_INIT'

export const FETCH_ORDERS_START = 'FETCH_START'
export const FETCH_ORDERS_FAIL = 'FETCH_FAIL'
export const FETCH_ORDERS_SUCCESS = 'FETCH_SUCCESS'
export const FETCH_ORDERS_INIT = 'FETCH_INIT'

export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAIL = 'AUTH_FAIL'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH'